### PR TITLE
Ignore existing prebackup deployments

### LINKED ISSUE #246: Backup reconciler fails if previous deployment for prebackuppods already exists
## Describe the bug

Backup reconciler fails if previous deployment for prebackuppods already exists

## Additional context

* the backups are completely stopped.

## Logs

If applicable, add logs to help explain your problem.
```console
2020-12-23T15:09:07.156+0100	INFO	controllers.Backup	starting pre backup pod	{"backup": "drupal-example-test1-master/backupjob-1608420480", "namespace": "drupal-example-test1-master", "name": "mariadb-prebackuppod"}
2020-12-23T15:09:07.164+0100	ERROR	controllers.Backup	error while handling pre backup pods	{"backup": "drupal-example-test1-master/backupjob-1608420480", "error": "error creating pre backup pods: deployments.apps \"mariadb-prebackuppod\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/vshn/k8up/executor.(*BackupExecutor).startBackup
	/home/runner/work/k8up/k8up/executor/backup.go:156
```

## Expected behavior

K8up should either
* Create new deployments with different name
* Update existing deployment
* Recreate deployment

## To Reproduce

1. Create PrebackupPod spec
2. Schedule backups

## Environment (please complete the following information):

- Image Version: v1.0.0-rc1
- K8s Version: v1.18
- K8s Distribution: Rancher

### PR DESCRIPTION
**Pull request by ccremer**
## Summary

This should ignore AlreadyExists errors when creating prebackup deployments.

Fixes #246 

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`,
      as they show up in the changelog
- [x] Link this PR to related issues.

### CODE REVIEW

**Comment by ccremer** [comment]
Note that, as long as prebackup deployments exist, they won't be updated. Should we add a prebackup controller that updates existing deployments upon changes?

**Comment by tobru** [comment]
> Should we add a prebackup controller that updates existing deployments upon changes?

Afaik in pre 1.0 of K8up this wasn't available?
It might make sense to have that in a future K8up release, yes.

**Comment by ccremer** [comment]
> Afaik in pre 1.0 of K8up this wasn't available?

I don't think so, but in https://github.com/vshn/k8up/issues/246#issuecomment-752009165 I understood we should be addressing this?

**Comment by ccremer** [comment]
@Kidswiss I'm getting lots of these after applying the fix (K8s 1.18)
```console
2020-12-30T14:24:02.043Z	INFO	controllers.Backup	adding job to the queue	{"backup": "default/backupjob-1609338240"}
2020-12-30T14:24:02.044Z	INFO	controllers.Backup	starting pre backup pod	{"backup": "default/backupjob-1609338240", "namespace": "default", "name": "mysqldump"}
2020-12-30T14:24:02.046Z	INFO	controllers.Backup	starting pre backup pod	{"backup": "default/backupjob-1609338240", "namespace": "default", "name": "mysqldump"}
2020-12-30T14:24:02.051Z	INFO	controllers.Backup	unexpected event during deployment watch 	{"backup": "default/backupjob-1609338240", "name": "mysqldump", "event type": "ADDED", "namespace": "default"}
2020-12-30T14:24:02.052Z	INFO	controllers.Backup	unexpected event during deployment watch 	{"backup": "default/backupjob-1609338240", "name": "mysqldump", "event type": "ADDED", "namespace": "default"}
2020-12-30T14:24:02.080Z	INFO	controllers.Backup	starting pre backup pod	{"backup": "default/backupjob-1609338240", "namespace": "default", "name": "mysqldump"}
2020-12-30T14:24:02.085Z	INFO	controllers.Backup	unexpected event during deployment watch 	{"backup": "default/backupjob-1609338240", "name": "mysqldump", "event type": "ADDED", "namespace": "default"}
2020-12-30T14:24:02.112Z	INFO	controllers.Backup	starting pre backup pod	{"backup": "default/backupjob-1609338240", "namespace": "default", "name": "mysqldump"}
2020-12-30T14:24:02.119Z	INFO	controllers.Backup	unexpected event during deployment watch 	{"backup": "default/backupjob-1609338240", "name": "mysqldump", "event type": "ADDED", "namespace": "default"}
2020-12-30T14:24:02.145Z	INFO	controllers.Backup	starting pre backup pod	{"backup": "default/backupjob-1609338240", "namespace": "default", "name": "mysqldump"}
2020-12-30T14:24:02.151Z	INFO	controllers.Backup	unexpected event during deployment watch 	{"backup": "default/backupjob-1609338240", "name": "mysqldump", "event type": "ADDED", "namespace": "default"}
```
Is that expected/ok? (Note: The backup jobs are all failing, since the they try to start the default "myprojec/restic" image)

To reproduce: 
```
make e2e_test
k apply -f config/samples/k8up_v1alpha1_prebackuppod.yaml
k apply -f config/samples/k8up_v1alpha1_schedule.yaml
```

**Comment by Kidswiss** [comment]
@ccremer I'd say we can change the code a bit so that the `ADDED` events aren't unexpected anymore. I haven't seen them before.

https://github.com/vshn/k8up/blob/master/prebackup/prebackup.go#L199

**Comment by Kidswiss** [comment]
> Note that, as long as prebackup deployments exist, they won't be updated. Should we add a prebackup controller that updates existing deployments upon changes?

I'd suggest to move discussions about improvements for the pre-backuppod stuff here: https://github.com/vshn/k8up/issues/137

I'm not so happy with the current implementation. It's more or less the same logic as legacy K8up uses and has a few flaws. For example if two pods are running at the same time in the same namespace and start pre-backuppods, the backup that finishes first will kill the deployments and could interrupt the second backup.

File: prebackup/prebackup.go [hunk 1]
```diff
@@ -219,6 +219,8 @@ func (p *PreBackup) waitForReady(watcher watch.Interface) error {
 			}
 			return fmt.Errorf("there was an unknown error while starting pre backup pod '%v/%v'", deployment.Namespace, deployment.Name)
 
+		case watch.Added:
+			// ignore this event, there would lots of them, but irrelevant.
```
Comment (ccremer) [inline prebackup/prebackup.go:223]: @Kidswiss do you think we should at least log the event with debug log level?

Comment (Kidswiss) [reply prebackup/prebackup.go:223]: Yeah why not, could be helpful for debugging stuff I guess.

**Comment by ccremer** [comment]
Regarding failing codeclimate check:
I have tested the fix with e2e testing tools locally, which isn't covered in the coverage.
I propose to skip a pseudo-test (a test just to increase coverage) if we think to overhaul prebackups anyway.
